site_name: Simber
site_description: A simple, minimal and powerful logger for Python
theme:
  name: material
  palette:
    scheme: preference
    primary: red
    accent: green
  icon:
    repo: fontawesome/brands/github
  language: en
  logo: assets/simber_white.png
  favicon: assets/simber_icon.png
  font:
    text: Rubik
    code: Fira Code
repo_name: deepjyoti30/simber
repo_url: https://github.com/deepjyoti30/simber
edit_uri: ''
markdown_extensions:
  - codehilite
  - markdown.extensions.codehilite:
      guess_lang: false
  - extra
nav:
  - Simber: index.md
  - architecture.md
  - logger.md
  - formatting.md
  - colors.md
  - streams.md