name: Deploy Docs

on:
  push:
    tags:
    branches:
      - 'master'

jobs:
  deploy:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v1
      - name: Push to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.KEY }}
          script: cd simber && git pull origin master && cd docs/en && mkdocs build --clean -d /var/www/simber